### ISSUE TITLE
runs-on action with "make --jobs" results in "GitHub Actions has encountered an internal error when running your job"

### ISSUE THREAD

**Issue by perrog** [runs-on/runs-on#107]
I'm not sure this is the right place to post issue for this GitHub action, but please close it if I'm wrong.

I'm using the action to run a work that compiles/builds in parallel. However, every attempt resulted in the following error:
```
The self-hosted runner: i-0a84e662bf9bae8b8 lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```
After 6th attempt I got this error:
```
GitHub Actions has encountered an internal error when running your job
```
My workflow configuration looks like this:
```
jobs:
  buildRelease:
    runs-on: [ ec2, linux, small ]
.
. then ultimately creating a container that calls make --jobs from inside the container
.
```

Why does I get internal error after 6th attempt?

What system load is allowed when you refer to "✅ Scalable. Handles bursts of multiple hundred jobs at once without issue. No concurrency limit" in the README.md file?

I've tried:
* make --jobs # does not work
* make --jobs --max-load 10 # does not work
* make --jobs 4 # does not work
* make --jobs 2 # unsure if this work(?) started to get GitHub Actions internal error

**Comment by crohr** [comment]
Hello, most often this error is due to an out of memory error on your runner. Can you tell more about the runner specification that you are using? Try with more memory until the error disappears. 

The scalable mention on the site related to being able to run hundreds of runners at once without any issue, which is different than running stuff in parallel on a single runner (which is only dependent on the type of runner you are selecting). 

Hope this helps
