### ISSUE TITLE
Option add to create Nat instance instead of nat-gateway!!

### ISSUE THREAD

**Issue by panduraju50** [runs-on/runs-on#122]
Dear team, 

  I would like to request add nat instance instead of nat-gateway. 
  
  https://fck-nat.dev/stable/deploying/#cloudformation | you can use fck nat as reference.

**Comment by crohr** [comment]
Hi @panduraju50, fck-nat has been evaluated, but is not convenient to setup just with CloudFormation, so for now only managed NAT gateways are officially supported. Note that Private networking will change in #115, so that it only uses one managed NAT gateway, and becomes an opt-in feature for runners. This will largely decrease costs, and ensure you only use NAT gateways when you really need it.

Hopefully it is a good enough compromise for you?

**Comment by panduraju50** [comment]
Thank you so much @crohr for the quick fix, mean time i was testing by tweaking the template yml 

May be some changes need to be done in the service as well. 

Issue with my modified template is it will deploy stack but the runners are not able to pick the ec2 instance.

Means the github runner waiting for runner for ever and I had to cancel the workflow job.

But Thank you again. 
[template-v2.3.2_text.txt](https://github.com/user-attachments/files/16688342/template-v2.3.2_text.txt)

**Comment by crohr** [comment]
Can you check that the route table for the private subnets is correct?
