### ISSUE TITLE
[Question] Potential issue with multiple runner labels?

### ISSUE THREAD

**Issue by qoomon** [runs-on/runs-on#127]
Hi, thanks for this awesome project.
Because I was working on a runner manager on my own, I'm wondering how you solved following issue.

How do you prevent using requesting an random runner if someone accidentally or by purpose just use the label `runs-on`
```yaml
  runs-on:
    - runs-on
```

My outcome was that you can not prevent this, therefore my recommendation or request would be to move to runners with a single label e.g.,  
- `runs-on: 2cpu-linux-x64@runs-on::${{ github.run_id }}`
- `runs-on: 2cpu-linux-x64@runs-on::run_id=${{ github.run_id }}`
- `runs-on: 2cpu-linux-x64@runs-on?run_id=${{ github.run_id }}`

```sh
./config.sh --url https://github.com/qoomon/sandbox --token XXXXXXXXXXXX --no-default-labels --labels '2cpu-linux-x64@runs-on::123456789'
```

**Comment by crohr** [comment]
Hi @qoomon, if someone assigns a subset of another job's labels to a job, then yes there is a risk that this job will steal the runner of that other job. But this is why the `run-id` label is recommended for inclusion, so that the set of labels are unique across workflow runs.

Using a single label is already supported:

```yaml
# this works in most (all?) repos
runs-on: "runs-on,runner=2cpu-linux-x64,etc"
```

But was deprecated because GitHub seemed have introduced a change to reject jobs with commas. That change seems to have been rejected by now, but to be safe I recommend the array syntax now.

If I had to add single label support to RunsOn, that would probably be with the safer `--` separator:

```yaml
runs-on: runs-on--runner=2cpu-linux-x64--run-id=${{ github.run_id }}--etc
```

How did you handle that for your own runner manager?

**Comment by qoomon** [comment]
My labels looks like this 
```yaml
runs-on: ubuntu-latest@2cpu-linux-x64@self-hosted
```

**Comment by crohr** [comment]
So what does your runner manager have that RunsOn doesn't (yet :))? Always interested in exchanging ideas.

**Comment by qoomon** [comment]
I'm working on idle instance pooling for faster job starts.

**Comment by crohr** [comment]
@qoomon pooling is hard to get right at scale, and the 30s delay is not that much an issue now. But let me know about your progress!
