### ISSUE TITLE
[Feature Request] Make Volume size/throughput/iops tunable on github job

### ISSUE THREAD

**Issue by filintod** [runs-on/runs-on#149]
It would be very nice to be able to tune the EBS volume more easily. At the moment, I'm seeing a fair amount of the cost are consumed by ebs costs and being able to use certain values for certain operations would be desired instead of having to hardcode the cloudformation stack.

**Comment by crohr** [comment]
Launch templates are fixed by the stack, and I don't want to create new ones at runtime because it adds some delay + can end going over the max quota. So best thing would be to add a third disk size maybe? I suppose this would handle 99% of use cases? Also keep in mind that you can ask for instances with local SSDs if you need more choices in disk sizes / performance.

**Comment by filintod** [comment]
ok, but there is no option to disable the ebs hdd, or there is? like if I select an instance with local nvme, it might cost a bit more, but if I still have to pay for the ebs, and not used, then it does not make much sense to go through this.

Let me know @crohr 

Thanks

**Comment by crohr** [comment]
The EBS volume is always required to boot the OS, but you can set throughput to the min (free) value of 125 for the default runner type in your stack and you’ll see that storage costs will largely decrease, at the cost of slightly higher boot times.
