### ISSUE TITLE
Feature: Retry on spot termination

### ISSUE THREAD

**Issue by alecmocatta** [runs-on/runs-on#160]
Approx 25% of our workflow runs experience a spot termination and have to be manually re-run in GitHub's UI.

Automatic re-running would save us time checking on runs, improve iteration times with faster merges, and improve our confidence in CI in general.

From https://github.com/runs-on/runs-on/issues/36#issuecomment-2001923792:
> The issue I see is that maybe some workflows have side effects and thus auto-restarting them might be problematic (like deploy jobs etc).

In our case, all jobs are idempotent and fine to auto-restart.

<details><summary><blockquote>Could you tell me a bit more about your jobs: what is their average duration? And the current instance type used?</blockquote></summary>

| name | config | duration |
|-|-|-|
| check | cpu=64,family=c7a+c7i+m7a+m7i+m7i-flex+c6a+c6i+m6a+m6i,hdd=50,image=ubuntu22-full-x64,spot=price-capacity-optimized,ssh=true | 4m 11s |
| test | cpu=128,family=c7a+c7i+m7a+m7i+m7i-flex,hdd=150,image=ubuntu22-full-x64,spot=price-capacity-optimized,ssh=true | 8m 19s |
| test-browser | runs-on,cpu=32,family=c7a+c7i+m7a+m7i+m7i-flex+c6a+c6i+m6a+m6i,hdd=50,image=ubuntu22-full-x64,spot=price-capacity-optimized,ssh=true | 4m 37s|
| e2e | cpu=32,family=c7a+c7i+m7a+m7i+m7i-flex+c6a+c6i+m6a+m6i,hdd=150,image=ubuntu22-full-x64,spot=price-capacity-optimized,ssh=true | 10m 36s |
| deploy | cpu=64,family=c7a+c7i+m7a+m7i+m7i-flex,hdd=150,image=ubuntu22-full-x64,spot=price-capacity-optimized,ssh=true | 29m 21s |

All on `us-east-1`.
</details>

**Comment by crohr** [comment]
This is definitely on the roadmap as the next big feature. Out of curiosity, did you try specifying the capacity-optimized spot policy? 25% interruption seems very high.

**Comment by alecmocatta** [comment]
Exciting to hear!

25% for 5 jobs works out at each job having ~6% chance of interruption, assuming independence. Is that higher than you'd expect?

I've not run numbers but I'm confident it's been higher in the last few weeks. Whether due to EC2 supply/demand or our jobs taking longer I'm not sure. We switched from `capacity-optimized` a while back but now you've prompted, we have indeed just switched back.

**Comment by filintod** [comment]
I gotta say that it's been more common lately to have instances interrupted and jobs cancelled. I'm on US-EAST-1

**Comment by colstrom** [comment]
> Exciting to hear!
> 
> 25% for 5 jobs works out at each job having ~6% chance of interruption, assuming independence. Is that higher than you'd expect?
> 
> I've not run numbers but I'm confident it's been higher in the last few weeks. Whether due to EC2 supply/demand or our jobs taking longer I'm not sure. We switched from `capacity-optimized` a while back but now you've prompted, we have indeed just switched back.

I _have_ run some numbers on this recently, and it does appear to be higher. Over the 90 days prior to 2024-11-01, in region `us-east-1`, tracking approximately 44k instances launched to run GHA workflows, roughly 600 (<1.4%) of were found to have a corresponding `BidEvictedEvent` (spot termination event). ~75% of those terminations occurred within 10 of those 90 days (11%).

This data is far from perfect, and has a fair bit of noise, since the number of workflows executed varies over time (with a general upward curve), and the instance type varies from workflow to workflow. The disruptions did seem to be concentrated on the `m7i-flex` and `c7i-flex` (and similar) instance types. And larger instances often correlate with longer-running workflows (but not always, of course), so that increases the exposure to spot disruption. So take the data with some skepticism. Your own numbers may vary wildly.
