### ISSUE TITLE
[Feature Request] How can run the Github runner as root instead of runner?

### ISSUE THREAD

**Issue by aledbf** [runs-on/runs-on#173]
The self-hosted runner can run as root by setting RUNNER_ALLOW_RUNASROOT=1. Some workflows require root access, and relying on sudo throughout requires many repository changes.
Thanks!

**Comment by crohr** [comment]
Hi @aledbf, I'm sorry but for now I don't think I will allow a setting for that use case. I try to keep things as similar as official runners, because every variation on a self-hosted product makes support more difficult. Hopefully the value brought by RunsOn outweighs the inconvenience of updating scripts!
