### ISSUE TITLE
Bug: custom RAM labels do not get added sometimes

### ISSUE THREAD

**Issue by yafanasiev** [runs-on/runs-on#193]
Runs-on version: 2.6.1

Hi! We were running a following configuration for about a month without any issues:

```yaml
    runs-on:
      - runs-on
      - env=<redacted>
      - spot=co
      - ram=32+64
      - runner=16cpu-linux-x64
      - run-id=${{ github.run_id }}
```

About a week ago, we noticed that sometimes the runner is launched without `ram` label (all other labels are present), so the job is not scheduled on it. We then updated to the latest version of runs-on (2.5.9 -> 2.6.1) and it did not help (it overall seems like the GitHub issue). All other runners that don't have `ram` label work perfectly fine. Could you please check what is the cause of this? Thanks in advance!

**Comment by crohr** [comment]
@yafanasiev Within your workflow file, do all jobs have the `ram` label, or do you have some that use a subset of the labels displayed here? If so, those other jobs most likely steal the runner triggered by the job with the `ram` label.

Please see https://runs-on.com/guides/troubleshoot/#all-jobs-are-queued-indefinitely-or-long-queuing-time-for-some-workflows for how to adapt your labels to ensure they are unique enough, and I believe it should fix your issue.

Otherwise could you please send additional details like workflow file definition (abbreviated if you want) at ops@runs-on.com ?

**Comment by yafanasiev** [comment]
@crohr thanks for the swift reply! You are spot on, another job in this workflow was recently modified and has exact same configuration __except__ the `ram` label. Thanks!
