### ISSUE TITLE
Deploying runs-on into preexisting VPC

### ISSUE THREAD

**Issue by yafanasiev** [runs-on/runs-on#198]
We have a quite specific networking setup in AWS with a lot of peering and Transit Gateway connections. And obviously, we would want `runs-on` runners to be able to access some of the internal resources using that networking setup. Problem is that since `runs-on` spins up it's own VPC we have to set up separate connections and routes instead of reusing the already existing ones. Would you be open to allow deployments into preexisting VPC? Or maybe, to widen this discussion a little bit, provide other deployment options so we could deploy just the minimal required stack  (AppRuner service + S3 bucket + whatever else) and supply things like VPC ID and subnets.

**Comment by crohr** [comment]
@yafanasiev I understand the concern, but 've always been against allowing this, because this would trigger a lot of support work on my side to make sure both configs work, and also answer support issues where the underlying cause might be an incorrect networking configuration. It also means a lot of integrated features (e.g. magic caching) could be lost / not working when using an existing VPC configuration.

I understand it is a bit painful to set up yet another route for the RunsOn VPC, but there are actually multiple clients doing this, and I believe it can be automated fairly easily based on the Cloudformation stack outputs (if not, let me know why).

Also AWS just released a new feature, which may or may not be useful in your case: https://aws.amazon.com/about-aws/whats-new/2024/12/access-vpc-resources-aws-privatelink/
